---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-app-secret
  namespace: dev
spec:
  encryptedData:
    API_KEY: AgCada3Vw8Wh/8FY6aB7sq1N4zisx67AqQt7ov2VziLSMBHxguq24/HgrWlLjlXk32l4F5iZGh2fZEQ33xf/yTc4zKkFnoKRDb/CMkNm/eV4TeOlc7t1QGQT+VEsB6phLVXRS+oJg2nFDzzHmMYwhlaRQCKnfM7jGrZSswTiq0w0RVtCWgykitlB1FQgip3vJJF8POW2q2MZQDuhxjPSW+sDHu1m/+1mZPZMaqtaBgYp/EIT2Q1kr4bBZKLTNSi+i2l4PnZuSDQ25wz4NRAdU0GwVRJ5W9+w8X117oBeWU99XF3wyTEhy2UjdkKsYZ2X2N0EFWXz6chWdD/mOYzDTEjUMIZrV1LzanIFo+8zeM38OI6Aq1h6vez0vMgy2hNKocn6LAvKyW/E/+hJp2iXo6+29TFgvCM9NjHnUhgDvbwHZ6znS9VLtNZpjS/rDXDc8648NoMdyQHQTL15BwiGK8T/z9Oji3R45IebzenJj1Fic3/I/b16/SPAXhn/CVfdWZqHt5shYTiKJJHiaJNgUygbOCleEz2RwYgyinwr1r0A5EfuHMdhqhrRgryEcaa0BJMeFJ3jlfmFt8ApDgW264BQeBK3nfIvsPSY0VB4eLJLMsQDD8TLq406ipt11sfkNegLr4X78V2ScZeskyVjVrB46jxk6NF6Wzunzl4LcHBGYWlhvS1Zbs7t0KX9FrP5gjKfyf5YB8kussJhfGcVdHaNX6FdREs=
  template:
    metadata:
      name: sample-app-secret
      namespace: dev
